backend/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stations, :path => :gasolineras

  root 'welcome#index'
  get '/gasolineras/:id/actualizar' => 'stations#update_station', as: :public_gas_update
  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

end

backend/app/models/station.rb
class Station < ActiveRecord::Base
  validates_presence_of :name, :street
end

backend/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

backend/app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy, :update_station]
  before_action :require_admin, except: [:index, :report, :update_station, :update]

  def index
    @stations = Station.all.order(updated_at: :desc)
  end

  def new
    @station = Station.new
  end

  def create
    @station = Station.new station_params
    if @station.save
      flash[:success] = 'Tu gasolinera ha sido creada'
      redirect_to stations_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @station.increment!(:count)
    if user_signed_in? && current_user.admin?
      if @station.update station_params
        flash[:success] = 'Tu gasolinera ha sido actualizada'
        redirect_to stations_path
      else
        render :edit
      end
    else
      if @station.update update_station_params
        flash[:success] = 'Tu gasolinera ha sido actualizada'
        redirect_to stations_path
      else
        render :edit
      end
    end

  end

  def destroy
    if @station.destroy
      flash[:danger] = 'Tu gasolinera ha sido destruida.'
    else
      flash[:warning] = 'Tu gasolinera no pudo ser destruida.'
    end

    redirect_to stations_path
  end

  private

  def station_params
    params.require(:station).permit(:name, :street, :lat, :lng, :phone, :gas, :message, :count)
  end

  def update_station_params
    params.require(:station).permit(:gas, :message, :count)
  end

  #simple encapsulation to not write this line all the time in required actions
  def set_station
    @station = Station.find(params[:id])
  end

  def require_admin
    return if user_signed_in? && current_user.admin?
    redirect_to root_path
  end

end

backend/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/stations_helper.rb
module StationsHelper
end

backend/app/views/layouts/_header.html.erb
<header>
  <div class="top-bar">
    <div class="top-bar-left">
      <%= link_to(root_path) do %>
        <strong class="korima-title">KorimaGAS</strong>
      <% end %>
    </div>
    <div class="top-bar-right">
      <% if user_signed_in?  %>
        <ul class="dropdown menu" data-dropdown-menu>
          <li>
            <a href="#"><%= current_user.email %> <%= '(Admin)' if current_user.admin? %></a>
            <ul class="menu vertical">
              <li><%= link_to "Editar Perfil", edit_user_registration_path %></li>
              <% if current_user.admin? %>
                <li><%= link_to "Add Gasolinera", (new_station_path) %></li>
              <% end %>
              <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</header>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "KorimaGAS" %></title>

    <link href='https://fonts.googleapis.com/css?family=Fjalla+One|Lato' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <%= yield %>

  </body>
</html>

backend/app/views/stations/_form.html.erb
<%= form_for @station do |f| %>
  <br>
  <div class="row">

    <div class="medium-10 medium-centered columns">
      <h2> Agregar Gasolinera</h2>

      <label>Nombre de Gasolinera
        <%= f.text_field :name, autofocus: true %>
      </label>
      <label>Calle
          <%= f.text_field :street, autofocus: true %>
      </label>
      <label>Hay Gasolina?
        <%= f.check_box :gas %>
      </label>

      <label>Mensaje
          <%= f.text_area :message, autofocus: true %>
      </label>

      <label>Telefono (opcional)
          <%= f.text_field :phone, autofocus: true %>
      </label>

      <div class="large-12 columns">
        <br><br>
        <p>Location (Opcional)</p>
        <label class="large-6 columns">Lat
            <%= f.text_field :lat, autofocus: true %>
        </label>
        <label class="large-6 columns">Lng
            <%= f.text_field :lng, autofocus: true %>
        </label>
      </div>

      <%= f.submit class: "button" %>

    </div>
    <%= link_to 'Volver a Gasolineras', stations_path %>
  </div>
<% end %>

backend/app/views/stations/edit.html.erb
<h1>Editar <%= @station.name %></h1>

<%= render "form" %>

backend/app/views/stations/index.html.erb
<div class="row text-center stations-list-title">
  <h2>Listado de Gasolineras</h2>
  <p>Si sabes el status de alguna, por favor actualiza!</p>
</div>

<ul class="stations-list">
    <% @stations.each do |station| %>
    <li class="station-item">
      <div class="station-title">
        <h2 class="station-name">
          <%= station.name %>
          <% if station.gas? %>
            <span class="yes-gas gas-status">Hay Gas!</span>
          <% else %>
          <span class="no-gas gas-status">No Gas</span>
          <% end %>
        </h2>
        <p><%= station.street %></p>
      </div>
      <strong><p>Mensaje:</p></strong>

      <div class="station-message">
        <p><%= station.message %></p>
      </div>
      <div class="station-updated">
        <p>Actualizado hace <strong><%= time_ago_in_words(station.updated_at) %></strong></p>
      </div>

      <div class="update-button-container">
        <%= link_to(public_gas_update_path(station)) do %>
          <button class="user-update-button">Quiero Actualizar!</button>
        <% end %>
      </div>

      <% if user_signed_in? && current_user.admin? %>
        <div class="station-buttons">
          <%= link_to 'Editar', edit_station_path(station) %>
          <%= link_to 'Borrar', station, method: :delete %>
        </div>
      <% end %>
    </li>
    <% end %>
</ul>

backend/app/views/stations/new.html.erb
<%= render 'form' %>

backend/app/views/stations/update_station.html.erb
<div class="row text-center stations-user-update-container">
  <h2>Actualizar <%= @station.name %></h2>
  <p>Gracias por contribuir a KorimaGAS!</p>

  <div class="row">
    <div class="small-11 large-12 columns small-centered">
      <%= form_for @station do |f| %>
        <br>
        <div class="row">


          <div class="medium-10 medium-centered columns">
            <div class="gas-status">
              <label>Hay Gasolina?
                <%= f.check_box :gas %>
              </label>
            </div>

            <label>Mensaje (140 caracteres)
                <%= f.text_area :message, autofocus: true, rows: 4 %>
            </label>

            <%= f.submit "Actualizar Gasolinera",  class: "user-update-button" %>

          </div>
          <br><br><br>
          <%= link_to 'Volver a Gasolineras', stations_path %>
        </div>
      <% end %>
    </div>
  </div>

</div>

backend/app/views/welcome/index.html.erb
<div class="welcome-banner">
  <div class="welcome-content">
    <h2>Encuentra  gasolina en Chihuahua</h2>
    <ul class="list-buttons">
      <li>
        <%= link_to(stations_path) do %>
          <button class="list-button">Ver gasolineras</button>
        <% end %>
      </li>
    </ul>
  </div>
</div>